name: Build every day at 6AM

on:
  schedule:
    - cron: "0 6 * * *" # Run at the end of every day.
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: "-X POST -H 'Authorization: token ${{ secrets.GH_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/lgmorand/lgmorand.github.io/pages/builds"
